### ISSUE TITLE
Scegliere messaggio social

### ISSUE THREAD

**Issue by aborruso** [ondata/ONUGovernotalianoDirittiUmani#10]
Ciao @dontyna a te la palla.

È il testo del messaggio twitter da inviare da ondatait

Cambialo come credi sia meglio

```
La traduzione in Italiano della lettera inviata dall'ONU al Governo italiano, con le preoccupazioni sul rispetto dei diritti umani.
Leggila e falla girare!
cc @Avvenire_Nei @RescueMed
https://bit.ly/onuchiamaitalia
```

**Comment by dontyna** [comment]
La traduzione in italiano della lettera inviata dall'ONU al nostro Governo, con le preoccupazioni sul rispetto dei diritti umani.
Leggila, ascoltala e diffondila nella tua rete 📢 
cc @Avvenire_Nei @RescueMed
https://bit.ly/onuchiamaitalia

**Comment by dontyna** [comment]
(Stavo cercando un hashtag da associare, #onuchiamaitalia forse?)

**Comment by giuragu** [comment]
> (Stavo cercando un hashtag da associare, #onuchiamaitalia forse?)

@dontyna @aborruso per me va benissimo.
Anche il tweet!

**Comment by aborruso** [comment]
Sì, è #onuchiamaitalia

Quindi è 

```
La traduzione in italiano della lettera inviata dall'ONU al nostro Governo, con le preoccupazioni sul rispetto dei diritti umani.
Leggila, ascoltala e diffondila nella tua rete 📢
cc @Avvenire_Nei @RescueMed
https://bit.ly/onuchiamaitalia #onuchiamaitalia
```
