### ISSUE TITLE
Pubblicare il testo della lettera from Ministro Interno to Pres. Cons.

### ISSUE THREAD

**Issue by giuragu** [ondata/ONUGovernotalianoDirittiUmani#13]
Decidere dove...Direi su altra pagina ma ben visibile in home...
@dontyna @aborruso 
Intanto vi condivido il [testo su cui lavorare](https://docs.google.com/document/d/1_B1YiCqtroPZiE8YBa1_yafbVwKFK73Q5lOjkwWYNuE/edit)

**Comment by giuragu** [comment]
Inserirei il link come una sorta di news qui 
![image](https://user-images.githubusercontent.com/12112056/58576350-67a89800-8244-11e9-9ffa-594333d9b59e.png)

**Comment by aborruso** [comment]
Ciao @giuragu ho costruito una base 

https://ondata.github.io/ONUGovernotalianoDirittiUmani/index_test.html

Se ti va bene puoi modificarlo tu stesso.

Ho fatto una copia del file index, che nel caso lo puoi sovrascrivere.

**Comment by giuragu** [comment]
> Ho fatto una copia del file index, che nel caso lo puoi sovrascrivere.

perfetto @aborruso. Ho aggiornato il testo e preferito indicare la data in altro formato. Cliccando sul titolo si arriva a alla pagina dedicata. In particolare ho inserito un ancora e per andare dritti al testo, non dovendo cioè scorrere la pagina partendo dall'intestazione di progetto.
Se così va bene si dovrebbe sostituire index con index_test e procedere con la issue #14. Farei tutto se possibile domani mattina

**Comment by giuragu** [comment]
Per il momento chiudiamo issue. Apriamo se necessario
