### ISSUE TITLE
predisporre testo introduttivo

### ISSUE THREAD

**Issue by aborruso** [ondata/ONUGovernotalianoDirittiUmani#7]
In home al momento si legge:

> La comunicazione è stata inviata dall'Alto Commissariato delle Nazioni Unite per i Diritti Umani nell'ambito delle cosiddette Procedure Speciali, meccanismi di monitoraggio e promozione dei diritti umani, di cui si serve il Consiglio per analizzare la situazione dei diritti umani in uno specifico Paese o specifiche questioni legate ai ...

Secondo si dovrebbe iniziare con:

>Giorno xx maggio tizio ha inviato a sempronio questo [documento](https://www.avvenire.it/c/attualita/Documents/ONUdirittiViolati.pdf) che riguarda ... 
>A nostro avviso meritava ampia diffusione e comprensione e abbiamo lanciato una [campagna di **traduzione in italiano**](http://blog.ondata.it/la-comunicazione-onu-al-governo-italiano-aiutaci-a-tradurla/) di gruppo, che ha portato al testo che riportiamo a seguire.

@giuragu te ne vuoi occupare tu?

**Comment by giuragu** [comment]
@aborruso si me ne occupo io

**Comment by giuragu** [comment]
@aborruso spero di aver colto bene il tuo input. Ho modificato l'introduzione sia nel titolo che nel testo...Chiudi tu se va bene

**Comment by aborruso** [comment]
grazie
