### ISSUE TITLE
Call to action nella intro

### ISSUE THREAD

**Issue by dontyna** [ondata/ONUGovernotalianoDirittiUmani#8]
Aggiungere la frase:

**E ora cosa puoi fare?**

- Condividere questo testo, farlo conoscere il più possibile 
- Usarlo per analisi, approfondimenti e studi (se lo fai raccontacelo)
- Usare la tua creatività e creare card con le frasi che ti hanno colpito di più (per esempio con Canva.com)

**Comment by giuragu** [comment]
@dontyna fatto! Dimmi se ok. Avrei anche una domanda. Se lo fari raccontacelo...come? Possiamo dare un consiglio (email. #, account tw @ondatait, altro...)

**Comment by aborruso** [comment]
@giuragu non ho capito la domanda

**Comment by aborruso** [comment]
L'ho capita @giuragu :)

Metti al limite sian indirizzo email che twitter

**Comment by giuragu** [comment]
@aborruso 
> Metti al limite sian indirizzo email che twitter

fatto. Passo e chiudo
